config/routes.rb
Rails.application.routes.draw do
  resources :votes
  get 'search/index'

  resources :answers
  mount Ckeditor::Engine => '/ckeditor'
  get 'portal/index'

  resources :questions do
    resources :question_comments
    get 'question_votes', to: 'question_votes#index'
    post 'question_votes', to: 'question_votes#handle', as: :question_vote
    resources :answers do
      get 'answer_votes', to: 'answer_votes#index'
      post 'answer_votes', to: 'answer_votes#handle', as: :answer_vote
      resources :answer_comments
    end
  end

  resources :users do
    member do
      get 'all_questions'
      get 'all_answers'
      get 'all_comments'
      get 'all_downvotes'
      get 'all_upvotes'
    end
  end

  resources :user_sessions, only: [:create, :destroy]

  delete '/logout', to: 'user_sessions#destroy', as: :log_out
  get '/login', to: 'user_sessions#new', as: :log_in

  get '/me', to: 'users#cur_user'

   root 'questions#index'

end

app/models/question.rb
require 'sanitize'
class Question < ActiveRecord::Base
  validates_presence_of :user_id
  validates_length_of :content, maximum: 1000
  validates_length_of :title, minimum: 5, maximum: 50
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :question_comments, dependent: :destroy
  has_many :question_votes, dependent: :destroy

  before_save :sanitize_content
  before_update :sanitize_content

  after_create :calculate_score

  after_find do |question|
    old_score = question.score
    question.calculate_score
    if old_score != question.score
      question.save
    end
  end


  searchable do
    string :title, :stored => true
    text :content, :stored => true
  end

  def points
    QuestionVote.where(question: self).sum(:attitude)
  end


  private

  def sanitize_content
    self.content = Sanitize.fragment(self.content, Sanitize::Config::RELAXED)
  end

  public

  def calculate_score
    logger.debug "question calculate score start"
    u = Float(question_votes.where(attitude: 1).length)
    v = Float(question_votes.where(attitude: -1).length)
    n = u + v

    vote_score = 0.0

    if (n != 0)
      p = u / n
      z = 1.96

      vote_score = 4 * n * (1 - p) * p + z ** 2
      vote_score = Math.sqrt(vote_score)
      vote_score = vote_score * z / n / 2
      vote_score = p + z ** 2 / 2 / n - vote_score
      vote_score = vote_score / (1 + z ** 2 / n)
    end

    answer_score = 0.0
    cnt = 0

    answers.order(score: :desc).each do |answer|
      cnt += 1
      answer_score += answer.score
      break if cnt == 99
    end

    begin
      date_diff = (DateTime.now - created_at).to_i
      logger.debug("date_diff=" + date_diff.to_s)
    rescue
      date_diff = 0
    end

    self.score = vote_score * 0.3 + answer_score * 0.7

    if date_diff < 10
      self.score += 0.02 * (10 - date_diff)
    end

    logger.debug "question calculate score success"

    self.score

  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :get_question, :only => [:show,:edit,:update,:destroy]
  authorize_resource
  # Action: Create a new comment to question
  def get_question
    @question = Question.find(params[:id])
  end
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    authorize! :create, @question
    if @question.save
      redirect_to @question
    else
      render 'new'
    end

  end

  # Display an comment box to current question
  def show
  end

  def index
    @sort = params.fetch(:sort, '2')
    @sort_strategy = @sort == '1' ?
        QuestionsHelper::DateSortStrategy::new :
        QuestionsHelper::PrioritySortStrategy::new

    @questions = @sort_strategy.acquire_sorted

  end

  # Display form to edit current question comment
  def edit
    authorize! :update, @question
  end

  # Action: Update given question comment
  def update
    if @question.update(question_params)
      redirect_to @question
      flash[:notice] = 'Question updated!'
    else
      render 'edit'
      flash[:notice] = 'Failed!'
    end
  end

  # Action: Destroy current question
  # Require question.user == current_user.login || Admin access
  def destroy
    @question.destroy
    redirect_to root_path
  end
  private
  def question_params
    params.require(:question).permit(:title, :content)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  class DateSortStrategy
    def acquire_sorted
      Question.order(updated_at: :desc).to_a
    end
  end

  class PrioritySortStrategy
    def acquire_sorted
      @questions = Question.all.to_a
      @questions.sort_by! do |question|
        - question.calculate_score
      end
    end
  end
end

app/views/questions/_errors.html.erb
<% if @question.errors.any? %>
    <div class="am-alert am-alert-warning" data-am-alert>
      <button type="button" class="am-close">&times;</button>
      <h3>警告</h3>

      <ul>
        <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/questions/_form.html.erb
<%= render 'errors' %>

<%= form_for @question do |f| %>


    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :content %>
    <%= f.cktext_area :content %>
    <%= f.submit %>

<% end %>

app/views/questions/_question_box.erb
<% if ! defined? show_link %>
    <% show_link = false %>
<% end %>

<% if detail %>

    <div class="am-u-sm-3">
      <% @vote = QuestionVote.user_vote(current_user, @question.id) %>
      <%= render 'votes/vote_box' %>
    </div>

    <div class="am-u-sm-9">
      <div style="display: inline-block;">
        <span class="am-monospace" style="font-size:1.2em; font-weight: bold; margin-bottom: 0px;">
          <% if show_link %>
              <%= link_to @question.title, @question %>
          <% else %>
              <%= @question.title %>
          <% end %>
        </span>
      </div>
      <div style="display: inline-block">
        <% if can? :update, @question %>
            <%= link_to '修改', edit_question_path(@question) %>
        <% end %>
        <% if can? :destroy, @question %>
            <%= link_to '删除', @question, action: :destroy, method: :delete, data: {confirm: 'Really?'} %>
        <% end %>
      </div>
      <div class="am-san-serif am-text-break" style="margin-top: 0.3em; margin-bottom: 0.3em;"><%= @question.content.html_safe%></div>
      <div style="display: inline-block">
        <%= content_tag "a", "#{@question.question_comments.length}条评论", id: "question_comment_link", class:"am-icon-comment-o", style:"font-size:1.4rem; color:#999;",
                        href: "javascript:void(0)",
                        data: {question_id: @question.id} %>
        <%= render 'shared/share_box' %>
      </div>
      <div style="display: inline-block; float: right">
        <span style="font-size: 1.4rem; color:rgb(153, 153, 153)">发布于<%= @question.created_at.strftime("%Y/%m/%d")%>&nbsp;</span>
        <%= link_to render(partial: 'users/user_name', locals: {user: @question.user}), @question.user, html_options = {style: "font-size:1.4rem;"} %>
      </div>
      <div id="question_comments_placeholder"></div>
      <hr>
    </div>

<% else %>
    <div class="am-u-sm-3"></div>
    <div class="am-u-sm-9 am-u-sm-offset-3">
      <div style="display: inline-block; float: left; margin-top: 3px;">
        <div style="display: inline-block; width: 50px; text-align: center">
          <span>#</span><br>
          <span>投票</span>
        </div>
        <div style="display: inline-block; width: 50px; text-align: center">
          <span><%= @question.answers.length %></span><br>
          <span>回答</span>
        </div>
        <div style="display: inline-block; width: 50px; text-align: center; margin-right: 10px;">
          <span><%= @question.question_comments.length %></span><br>
          <span>评论</span>
        </div>
      </div>
      <div>
        <div>
          <%= link_to @question.title, @question, style: "font-size: 1.2em"%>
        </div>
        <div style="font-size: 0.9em; text-align: right">
          <span>发布于 <%= @question.created_at.strftime("%Y/%m/%d") %></span>
          <%= link_to render(partial: 'users/user_name', locals: {user: @question.user}), @question.user %>
        </div>
      </div>
      <hr>
    </div>

<% end %>

app/views/questions/edit.html.erb
<% content_for :head do %>
    <title>修改问题-者也</title>
<% end %>

<%= render 'errors' %>

<div class="am-u-sm-3"></div>
<div class="am-u-sm-9 am-u-sm-offset-3">
  <span class="am-monospace" style="font-weight: bold; font-size: 1.1em">修改问题</span>
  <hr style="margin-top: 0px;">
  <%= form_for @question, html: {'data-am-validator'=> true}  do |f| %>
      <div class="am-input-group am-input-group-primary" style="margin-bottom: 5px">
        <span class="am-input-group-label"><i class="am-icon-quote-left am-icon-fw"></i></span>
        <%= f.text_field :title, class: "am-form-field", placeholder:"标题", minlength: 5 %>
      </div>
      <div style="margin-bottom: 5px">
        <%= f.cktext_area :content%><br>
      </div>
      <%= f.submit "提交", class:"am-btn am-btn-primary", style:"float:right"%>
  <% end %>
  <%= button_to '返回', @question, action:"show", method: :get , :class => 'am-btn', :style => 'float:right; margin-right:5px'%>
</div>

app/views/questions/index.html.erb
<% content_for :head do %>
    <title>首页-者也</title>
<% end %>

<div class="am-u-sm-3"></div>
<div class="am-u-sm-9 am-u-sm-offset-3">
  <div style="display: inline-block; vertical-align: middle">
    <span class="am-monospace" style="font-weight: bold; font-size: 1.1em">热门问答</span>
  </div>
  <div style="display: inline-block; float: right; vertical-align: middle">
    <% if params[:sort] == "1" %>
        <div class="am-btn-group doc-js-btn-1" data-am-button>
          <label class="am-btn am-btn-secondary am-btn-sm am-active">
            <input type="radio" name="options" value="1" id="option1" checked> 综合排序
          </label>
          <label class="am-btn am-btn-secondary am-btn-sm">
            <input type="radio" name="options" value="2" id="option2"> 时间排序
          </label>
          <!--
          <label class="am-btn am-btn-secondary am-btn-sm">
            <input type="radio" name="options" value="3" id="option3"> 迷之排序
          </label>
          -->
        </div>
    <% else %>
        <div class="am-btn-group doc-js-btn-1" data-am-button>
          <label class="am-btn am-btn-secondary am-btn-sm">
            <input type="radio" name="options" value="1" id="option1"> 综合排序
          </label>
          <label class="am-btn am-btn-secondary am-btn-sm am-active">
            <input type="radio" name="options" value="2" id="option2" checked> 时间排序
          </label>
          <!--
          <label class="am-btn am-btn-secondary am-btn-sm">
            <input type="radio" name="options" value="3" id="option3"> 迷之排序
          </label>
          -->
        </div>
    <% end %>
  </div>
  <hr style="margin: 0.5em 0 0.5em;">
  <% @questions.each do |question| %>
      <div style="display: inline-block; float: left; padding-top: 3px;">
        <div style="display: inline-block; width: 50px; text-align: center">
          <% @vote = QuestionVote.user_vote(current_user, question.id) %>
          <div style="color:#6a737c; margin-bottom: -3px;"><%= @vote.points %></div>
          <div style="color:#6a737c; font-size: 0.8em;">投票</div>
        </div>
        <div style="display: inline-block; width: 50px; text-align: center">
          <% if question.answers.length >= 10 %>
              <div style="color: #c52f24; margin-bottom: -3px;"><%= question.answers.length %></div>
              <div style="color: #c52f24; font-size: 0.8em;">回答</div>
          <% elsif question.answers.length >=5 %>
              <div style="color: #CF7721; margin-bottom: -3px;"><%= question.answers.length %></div>
              <div style="color: #CF7721; font-size: 0.8em;">回答</div>
          <% elsif question.answers.length >=1 %>
              <div style="color: #45A163; margin-bottom: -3px;"><%= question.answers.length %></div>
              <div style="color: #45A163; font-size: 0.8em;">回答</div>
          <% else %>
              <div style="color: #6a737c; margin-bottom: -3px;"><%= question.answers.length %></div>
              <div style="color: #6a737c; font-size: 0.8em;">回答</div>
          <% end %>
        </div>
        <div style="display: inline-block; width: 50px; text-align: center; margin-right: 10px">
          <div style="color: #6a737c; margin-bottom: -3px;"><%= question.question_comments.length %></div>
          <div style="color: #6a737c; font-size: 0.8em;">评论</div>
        </div>
      </div>
      <div>
        <div>
          <%= link_to question.title, question, style: "font-size: 1.2em"%>
        </div>
        <div style="font-size: 0.8em; text-align: right">
          <span>发布于 <%= question.created_at.strftime("%Y/%m/%d") %></span>
          <%= link_to question.user.login, question.user %>
        </div>
      </div>
      <hr style="margin: 0.5em 0 0.5em;">
  <% end %>

</div>


<script>
  // 获取选中的值
  $(function() {
    var $radios = $('[name="options"]');
    $radios.on('change',function() {
      console.log('单选框当前选中的是：', $radios.filter(':checked').val());
      window.location.href = changeURLArg(window.location.href, 'sort', $radios.filter(':checked').val());
    });
  });
</script>


<script>
  function changeURLArg(url, arg, arg_val) {
    var pattern = arg + '=([^&]*)';
    var replaceText = arg + '=' + arg_val;
    if (url.match(pattern)) {
      var tmp = '/(' + arg + '=)([^&]*)/gi';
      tmp = url.replace(eval(tmp), replaceText);
      return tmp;
    }else{
      if(url.match('[\?]')){
        return url + '&' + replaceText;
      }else{
        return url + '?' + replaceText;
      }
    }
    return url + '\n' + arg + '\n' + arg_val;
  }
</script>

<script>
  $(document).ready(function() {
        console.log(window.location.href);
        console.log("log");
      }
  );
</script>

<% logger.debug("hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh") %>
<% logger.debug(request.fullpath) %>
<% logger.debug("hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh") %>

app/views/questions/new.html.erb
<% content_for :head do %>
    <title>用户提问-者也</title>
<% end %>

<%= render 'errors' %>
<div class="am-u-sm-3"></div>
<div class="am-u-sm-9 am-u-sm-offset-3">
  <span class="am-monospace" style="font-weight: bold; font-size: 1.1em">用户提问</span>
  <hr style="margin-top: 0px;">
  <%= form_for @question, html: {'data-am-validator'=> true} do |f| %>
      <div class="am-input-group am-input-group-primary" style="margin-bottom: 5px">
        <span class="am-input-group-label"><i class="am-icon-quote-left am-icon-fw"></i></span>
        <%= f.text_field :title, class: "am-form-field", placeholder:"标题", minlength: 5 %>
      </div>
      <%= f.cktext_area :content%>
      <%= f.submit "提交", class:"am-btn am-btn-primary", style:"float:right; margin-top:10px;"%>
  <% end %>
  <!--
  <%= button_to '返回', questions_path, :class => 'am-btn', :style => 'float:right; margin-right:5px'%>
  -->
</div>

app/views/questions/show.html.erb
<% content_for :head do %>
    <title><%= @question.title %>-者也</title>
<% end %>

<%= render partial: 'question_box', locals: {detail: true} %>
<%= content_tag "div", "Loading...", id: "answer_box", data: {question_id: @question.id, sort: params[:sort]} %>
<% if current_user %>
<%= content_tag "div", "Loading...", id: "new_answer_box", data: {question_id: @question.id, user_login: current_user.login} %>
<% end %>