config/routes.rb
Rails.application.routes.draw do
  resources :votes
  get 'search/index'

  resources :answers
  mount Ckeditor::Engine => '/ckeditor'
  get 'portal/index'

  resources :questions do
    resources :question_comments
    get 'question_votes', to: 'question_votes#index'
    post 'question_votes', to: 'question_votes#handle', as: :question_vote
    resources :answers do
      get 'answer_votes', to: 'answer_votes#index'
      post 'answer_votes', to: 'answer_votes#handle', as: :answer_vote
      resources :answer_comments
    end
  end

  resources :users do
    member do
      get 'all_questions'
      get 'all_answers'
      get 'all_comments'
      get 'all_downvotes'
      get 'all_upvotes'
    end
  end

  resources :user_sessions, only: [:create, :destroy]

  delete '/logout', to: 'user_sessions#destroy', as: :log_out
  get '/login', to: 'user_sessions#new', as: :log_in

  get '/me', to: 'users#cur_user'

   root 'questions#index'

end

app/models/user.rb
class User < ActiveRecord::Base
    acts_as_authentic
    has_many :votes, dependent: :destroy
    has_many :questions, dependent: :destroy
    has_many :answers, dependent: :destroy
    has_many :comments, dependent: :destroy

    after_create :calculate_score

    after_find do |user|
        old_score = user.score
        user.calculate_score
        if old_score != user.score
            user.save
        end
    end

    def all_upvotes_received
        upvotes_count =
            self.questions.inject(0) do |count, q|
                count += q.question_votes.where(attitude: 1).length
            end
        self.answers.inject(upvotes_count) do |count, q|
            count += q.answer_votes.where(attitude: 1).length
        end

    end

    public
      def calculate_score
          logger.debug "user calculate score start"

          self.score = 0.0
          cnt = 0

          answers.order(score: :desc).each do |answer|
              cnt += 1
              self.score += answer.score
              break if cnt == 9
          end

          self.score += 1
          self.score /= 10

          logger.debug "user calculate score success"

          self.score

      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  authorize_resource :except => [:cur_user, :all_questions, :all_answers, :all_comments, :all_upvotes, :all_downvotes]

  respond_to :html, :js
  # Display all users
  # Require admin access
  def index

  end
  # Action: Create a new user
  # params.require(:user).permit(:login, :password, :password_confirmation)
  def create
    @user = User.new(users_params)
    @user.admin = @user.login == 'admin'
    @user.save
  end

  # Display registration form
  def new
    @user = User.new
    render 'new', layout: 'simple'
  end

  # Display info about certain user
  def show
    @user = User.find(params[:id])
  end

  # Display form to edit current user's info
  def edit
    @user = User.find(params[:id])
  end

  # Action: Update given user's infos
  def update
    @user = User.find(params[:id])
    if @user.update(user_info_params)
      redirect_to @user
    else
      render 'edit'
    end

  end

  def cur_user
    redirect_to current_user
  end

  def all_questions
    @user = User.find(params[:id])
    @questions = @user.questions
    authorize! :read, Question
  end

  def all_answers
    @user = User.find(params[:id])
    @answers = @user.answers
    authorize! :read, Answer
  end

  def all_comments
    @user = User.find(params[:id])
    @comments = @user.comments
    authorize! :read, Comment
  end

  def all_upvotes
    @user = User.find(params[:id])
    @upvotes = Vote.where({user: @user, attitude: 1})
    authorize! :read, Vote
  end

  def all_downvotes
    @user = User.find(params[:id])
    @downvotes = Vote.where({user: @user, attitude: -1})
  end

  # Action: Destroy certain user(not logout)
  # Require admin access
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def users_params
    # Todo: Add other user info required by register here
    params.require(:user).permit(:login, :password, :password_confirmation)
  end

  def user_info_params
    params.require(:user).permit(:gender, :realname, :birthday, :address, :self_introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_name.html.erb
<% if defined? user %>
    <% @user = user %>
<% end %>
<%= @user.login %>
<% if @user.admin? %>
    <span class="am-badge am-badge-primary am-round">管理员</span>
<% end %>

app/views/users/all_answers.html.erb
<% content_for :head do %>
    <title><%= @user.login %>的回答-者也</title>
<% end %>

<div class="am-u-sm-3"></div>
<div class="am-u-sm-9 am-u-sm-offset-3">
  <span class="am-monospace" style="font-weight: bold; font-size: 1.1em"><%= render partial: 'users/user_name' %>的回答(<%= @answers.length %>)</span>
  <hr style="margin-top: 0px;">
</div>
<% @answers.each do |answer| %>
    <% @answer = answer %>
    <%= render partial: 'answers/answer_box', locals: {detail: true} %>
<% end %>

app/views/users/all_comments.html.erb
<% content_for :head do %>
    <title><%= @user.login %>的评论-者也</title>
<% end %>

<div class="am-u-sm-3"></div>
<div class="am-u-sm-9 am-u-sm-offset-3">
  <span class="am-monospace" style="font-weight: bold; font-size: 1.1em"><%= render partial: 'users/user_name' %>的评论(<%= @comments.length %>)</span>
  <hr style="margin-top: 0px;">
</div>
<% @comments.each do |comment| %>
    <% @comment = comment %>
    <% if @comment.type == 'QuestionComment' %>
        <% @question=@comment.question %>
        <div class="am-u-sm-3"></div>
        <div class="am-u-sm-9 am-u-sm-offset-3">
          <span style="color:#999; font-size: 1.4rem;">
            <%= @user.login %>评论的问题
          </span>
          <div class="am-monospace" style="font-size:1.2em; font-weight: bold; margin-bottom: -10px;">
            <%= link_to @question.title, @question %>
          </div>
          <div>
            <ul class="am-comments-list am-comments-list-flip" id="commentslist">
              <%= render partial: 'comments/show' %>
            </ul>
          </div>
          <hr>
        </div>
    <% else %>
        <% @answer=@comment.answer %>
        <div class="am-u-sm-3"></div>
        <div class="am-u-sm-9 am-u-sm-offset-3">
          <span style="color:#999; font-size: 1.4rem;">
            <%= @user.login %>评论的回答
          </span>
          <div class="am-monospace" style="font-size:1.1em; font-weight: bold; margin-bottom: 0px;">
            <%= link_to @answer.question.title, @answer.question %>
          </div>
          <div style="margin-bottom: -10px;">
            <%= @answer.content.html_safe %>
          </div>
          <div>
            <ul class="am-comments-list am-comments-list-flip" id="commentslist">
              <%= render partial: 'comments/show' %>
            </ul>
          </div>
          <hr>
        </div>
    <% end %>
<% end %>

app/views/users/all_downvotes.erb
<% content_for :head do %>
    <title><%= @user.login %>反对的-者也</title>
<% end %>

<div class="am-u-sm-3"></div>
<div class="am-u-sm-9 am-u-sm-offset-3">
  <span class="am-monospace" style="font-weight: bold; font-size: 1.1em"><%= render partial: 'users/user_name' %>反对的(<%= @downvotes.length %>)</span>
  <hr style="margin-top: 0px;">
</div>
<% @downvotes.each do |downvote| %>
    <% @downvote = downvote %>
    <% if @downvote.type == 'QuestionVote' %>
        <% @question = @downvote.question %>
        <div class="am-u-sm-3"></div>
        <div class="am-u-sm-9 am-u-sm-offset-3">
          <span style="color:#999; font-size: 1.4rem;">
            <%= @user.login %>反对的问题
          </span>
        </div>
        <%= render partial: 'questions/question_box', locals: {detail: true, show_link: true} %>
    <% else %>
        <% @answer = @downvote.answer %>
        <div class="am-u-sm-3"></div>
        <div class="am-u-sm-9 am-u-sm-offset-3">
          <span style="color:#999; font-size: 1.4rem;">
            <%= @user.login %>反对的回答
          </span>
        </div>
        <%= render partial: 'answers/answer_box', locals: {detail: true} %>
    <% end %>
<% end %>

app/views/users/all_questions.html.erb
<% content_for :head do %>
    <title><%= @user.login %>的提问-者也</title>
<% end %>

<div class="am-u-sm-3"></div>
<div class="am-u-sm-9 am-u-sm-offset-3">
  <span class="am-monospace" style="font-weight: bold; font-size: 1.1em"><%= render partial: 'users/user_name' %>的提问(<%= @questions.length %>)</span>
  <hr style="margin-top: 0px;">
</div>
<% @questions.each do |question| %>
<% @question = question %>
<%= render partial: 'questions/question_box', locals: {detail: true, show_link:true} %>
<% end %>

app/views/users/all_upvotes.erb
<% content_for :head do %>
    <title><%= @user.login %>赞成的-者也</title>
<% end %>

<div class="am-u-sm-3"></div>
<div class="am-u-sm-9 am-u-sm-offset-3">
  <span class="am-monospace" style="font-weight: bold; font-size: 1.1em"><%= render partial: 'users/user_name' %>赞成的(<%= @upvotes.length %>)</span>
  <hr style="margin-top: 0px;">
</div>
<% @upvotes.each do |upvote| %>
    <% @upvote = upvote %>
    <% if @upvote.type == 'QuestionVote' %>
        <% @question = @upvote.question %>
        <div class="am-u-sm-3"></div>
        <div class="am-u-sm-9 am-u-sm-offset-3">
          <span style="color:#999; font-size: 1.4rem;">
            <%= @user.login %>赞成的问题
          </span>
        </div>
        <%= render partial: 'questions/question_box', locals: {detail: true, show_link: true} %>
    <% else %>
        <% @answer = @upvote.answer %>
        <div class="am-u-sm-3"></div>
        <div class="am-u-sm-9 am-u-sm-offset-3">
          <span style="color:#999; font-size: 1.4rem;">
            <%= @user.login %>赞成的回答
          </span>
        </div>
        <%= render partial: 'answers/answer_box', locals: {detail: true} %>
    <% end %>
<% end %>

app/views/users/create.js.erb
<% if @user.errors.any? %>
alert("<%= j @user.errors.full_messages.join('\n') %>");
<% else %>
window.parent.location.reload();
<% end %>

app/views/users/edit.html.erb
<% content_for :head do %>
    <title>编辑个人资料-者也</title>
<% end %>

<div class="am-u-sm-3"></div>
<div class="am-u-sm-9 am-u-sm-offset-3">
  <span class="am-monospace" style="font-weight: bold; font-size: 1.1em">修改个人信息</span>
  <hr style="margin-top: 0px;">
  <div>
    <span style="color: #666; font-weight: 700"><i class="am-icon-angellist am-icon-fw"></i>个人成就</span>
    <div style="padding-left: 40px; color: #777; font-size: 0.9em;">获得
      <i class="am-icon-thumbs-o-up am-icon-fw"></i>
      <span style="font-weight: bold"><%= @user.all_upvotes_received %> </span>赞成
      <i class="am-icon-star am-icon-fw"></i>
      <span style="font-weight: bold"><%= (@user.score * 100).round %> </span>积分
    </div>
  </div>
  <div style="margin-top: 20px;">
    <span style="color: #666; font-weight: 700"><i class="am-icon-bar-chart-o am-icon-fw"></i>统计信息</span>
    <div style="padding-left: 40px; color: #777; font-size: 0.9em;">
      <%= link_to all_questions_user_path(@user) do %>
          <i class="am-icon-lightbulb-o am-icon-fw"></i>
          <span>提问(<%= @user.questions.length %>)</span>
      <% end %>
      <%= link_to all_answers_user_path(@user) do %>
          <i class="am-icon-sticky-note-o am-icon-fw" style="margin-left: 10px;"></i>
          <span>回答(<%= @user.answers.length %>)</span>
      <% end %>
      <%= link_to all_comments_user_path(@user) do %>
          <i class="am-icon-comment-o am-icon-fw" style="margin-left: 10px;"></i>
          <span>评论(<%= @user.comments.length %>)</span>
      <% end %>
      <%= link_to all_upvotes_user_path(@user) do %>
          <i class="am-icon-thumbs-o-up am-icon-fw" style="margin-left: 10px;"></i>
          <span>赞成(<%= @user.votes.where(attitude: 1).length %>)</span>
      <% end %>
      <%= link_to all_downvotes_user_path(@user) do %>
          <i class="am-icon-thumbs-o-down am-icon-fw" style="margin-left: 10px;"></i>
          <span>反对(<%= @user.votes.where(attitude: -1).length %>)</span>
      <% end %>
    </div>
  </div>
  <div style="margin-top: 20px;">
    <span style="color: #666; font-weight: 700; margin-bottom: 5px;"><i class="am-icon-list-ul am-icon-fw"></i>详细资料</span>
    <%= form_for @user do |f| %>
        <div class="am-input-group am-input-group-primary" style="margin-top: 5px;">
          <span class="am-input-group-label"><i class="am-icon-user am-icon-fw"></i></span>
          <%= f.text_field :realname, class: "am-form-field", placeholder:"真实姓名", style:"width:100px;"%>
        </div>
        <div style="display: inline-block; background-color: #0e90d2; padding-top: 3.5px; margin-right: -2px; height: 37.2px; width:53px; text-align: center; margin-top: 6px;">
          <i class="am-icon-venus-mars am-icon-fw" style="color:white;"></i>
        </div>
        <div class="am-btn-group doc-js-btn-1" data-am-button>
          <label class="am-btn am-btn-primary <%= @user.gender ? "am-active" : ""%>">
            <%= f.radio_button :gender, 'true' %>男
          </label>
          <label class="am-btn am-btn-primary <%= (@user.gender == false) ? "am-active" : ""%>">
            <%= f.radio_button :gender, 'false' %>女
          </label>
        </div>
        <div class="am-input-group am-input-group-primary" style="margin-top: 6px;">
          <span class="am-input-group-label"><i class="am-icon-birthday-cake am-icon-fw"></i></span>
          <div style="margin-left: 2px; padding-top: 1.1px;">
            <%= f.date_select :birthday, :start_year => 1930, :end_year => 2016, class: "am-form-field"%>
          </div>
        </div>
        <div class="am-input-group am-input-group-primary" style="margin-top: 6px">
          <span class="am-input-group-label"><i class="am-icon-map am-icon-fw"></i></span>
          <%= f.text_field :address, class: "am-form-field", placeholder:"地址" %>
        </div>
        <div style="margin-top: 6px">
          <%= f.text_area :self_introduction, style:"width:100%; border: 1px solid rgb(14, 144, 210)", placeholder:"个人介绍" %><br>
        </div>
        <%= f.submit "提交", class:"am-btn am-btn-primary", style:"float:right"%>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= form_for @user, remote: true do |f| %>
    <%= render 'shared/errors', object: @user %>
    <div class="am-input-group am-input-group-primary" style="margin-bottom: 5px">
      <span class="am-input-group-label"><i class="am-icon-user am-icon-fw"></i></span>
      <%= f.text_field :login, class: "am-form-field", placeholder:"登录帐号" %>
    </div>

    <div style="margin-bottom: 5px">
      <%= f.password_field :password, class: "am-form-field", placeholder:"密码", style:"border-color:rgb(14, 144, 210)" %>
    </div>

    <div style="margin-bottom: 5px">
      <%= f.password_field :password_confirmation, class: "am-form-field", placeholder:"确认密码", style:"border-color:rgb(14, 144, 210)" %>
    </div>

    <%= f.submit '注册', class:"am-btn am-btn-primary", style:"float:right" %>
<% end %>

app/views/users/show.html.erb
<% content_for :head do %>
    <title><%= @user.login %>的主页-者也</title>
<% end %>


<div class="am-u-sm-3"></div>
<div class="am-u-sm-9 am-u-sm-offset-3">
  <span class="am-monospace" style="font-weight: bold; font-size: 1.1em"><%= @user.login %>的主页</span>
  <hr style="margin-top: 0px;">
  <div>
    <span style="color: #666; font-weight: 700"><i class="am-icon-angellist am-icon-fw"></i>个人成就</span>
    <div style="padding-left: 40px; color: #777; font-size: 0.9em;">获得
      <i class="am-icon-thumbs-o-up am-icon-fw"></i>
      <span style="font-weight: bold"><%= @user.all_upvotes_received %> </span>赞成
      <i class="am-icon-star am-icon-fw"></i>
      <span style="font-weight: bold"><%= (@user.score * 100).round %> </span>积分
    </div>
  </div>
  <div style="margin-top: 20px;">
    <span style="color: #666; font-weight: 700"><i class="am-icon-bar-chart-o am-icon-fw"></i>统计信息</span>
    <div style="padding-left: 40px; color: #777; font-size: 0.9em;">
      <%= link_to all_questions_user_path(@user) do %>
          <i class="am-icon-lightbulb-o am-icon-fw"></i>
          <span>提问(<%= @user.questions.length %>)</span>
      <% end %>
      <%= link_to all_answers_user_path(@user) do %>
          <i class="am-icon-sticky-note-o am-icon-fw" style="margin-left: 10px;"></i>
          <span>回答(<%= @user.answers.length %>)</span>
      <% end %>
      <%= link_to all_comments_user_path(@user) do %>
          <i class="am-icon-comment-o am-icon-fw" style="margin-left: 10px;"></i>
          <span>评论(<%= @user.comments.length %>)</span>
      <% end %>
      <%= link_to all_upvotes_user_path(@user) do %>
          <i class="am-icon-thumbs-o-up am-icon-fw" style="margin-left: 10px;"></i>
          <span>赞成(<%= @user.votes.where(attitude: 1).length %>)</span>
      <% end %>
      <%= link_to all_downvotes_user_path(@user) do %>
          <i class="am-icon-thumbs-o-down am-icon-fw" style="margin-left: 10px;"></i>
          <span>反对(<%= @user.votes.where(attitude: -1).length %>)</span>
      <% end %>
    </div>
  </div>
  <div style="margin-top: 20px;">
    <span style="color: #666; font-weight: 700"><i class="am-icon-list-ul am-icon-fw"></i>详细资料</span>
    <% if can? :update, @user %>
        <%= link_to '修改', edit_user_path(@user) %>
    <% end %>
    <% if can? :destroy, @user %>
        <%= link_to '删除', user_path(@user), method: :delete, data: {confirm: 'Really?'} %>
    <% end %>
    <div style="padding-left: 40px; color: #777; font-size: 0.9em;">
      <div><i class="am-icon-user am-icon-fw"></i> 真实姓名：<%= @user.realname %></div>
      <div>
        <i class="am-icon-venus-mars am-icon-fw"></i>
        <% if @user.gender %>
            <span>性别：男</span><br>
        <% elsif @user.gender==false %>
            <span>性别：女</span><br>
        <% else %>
            <span>性别：</span><br>
        <% end %>
      </div>
      <div><i class="am-icon-birthday-cake am-icon-fw"></i> 生日：<%= @user.birthday %></div>
      <div><i class="am-icon-map-o am-icon-fw"></i> 地址：<%= @user.address %></div>
      <div><i class="am-icon-pencil-square-o am-icon-fw"></i> 个人简介：<%= @user.self_introduction %></div>
    </div>
  </div>

</div>