config/routes.rb
Rails.application.routes.draw do
  resources :votes
  get 'search/index'

  resources :answers
  mount Ckeditor::Engine => '/ckeditor'
  get 'portal/index'

  resources :questions do
    resources :question_comments
    get 'question_votes', to: 'question_votes#index'
    post 'question_votes', to: 'question_votes#handle', as: :question_vote
    resources :answers do
      get 'answer_votes', to: 'answer_votes#index'
      post 'answer_votes', to: 'answer_votes#handle', as: :answer_vote
      resources :answer_comments
    end
  end

  resources :users do
    member do
      get 'all_questions'
      get 'all_answers'
      get 'all_comments'
      get 'all_downvotes'
      get 'all_upvotes'
    end
  end

  resources :user_sessions, only: [:create, :destroy]

  delete '/logout', to: 'user_sessions#destroy', as: :log_out
  get '/login', to: 'user_sessions#new', as: :log_in

  get '/me', to: 'users#cur_user'

   root 'questions#index'

end

app/views/shared/_backtotop.html.erb
<div data-am-widget="gotop" class="am-gotop am-gotop-fixed" >
  <a href="#top" title="回到顶部">
    <span class="am-gotop-title">回到顶部</span>
    <i class="am-gotop-icon am-icon-chevron-up"></i>
  </a>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div class="am-alert am-alert-warning" data-am-alert>
      <button type="button" class="am-close">&times;</button>
      <h3>警告</h3>

      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="am-g am-g-collapse" style="bottom: 0; width: 100%; margin-top: 30px;">
  <div class="am-u-sm-2"></div>
  <div class="am-u-sm-8 am-u-sm-offset-2">
    <hr>
    <div style="display: inline-block">
      <span style="color:#999">
        者也，一起提高姿势水平！
      </span><br>
      <span style="color:#999">
        © 2016 Morocco Group. Developed with Ruby on Rails.
      </span>
    </div>
    <div style="display: inline-block;float: right">
      <button type="button" class="am-btn am-btn-default am-btn-sm" style="border:1px transparent; background-color: transparent; color:#999" data-am-modal="{target: '#my-alert1'}">
        联系我们
      </button>
      <div class="am-modal am-modal-alert"  id="my-alert1">
        <div class="am-modal-dialog">
          <div class="am-modal-hd">联系我们</div>
          <div class="am-modal-bd">
            Github：https://github.com/zheye-dev/zheye
          </div>
          <div class="am-modal-footer">
            <span class="am-modal-btn">确定</span>
          </div>
        </div>
      </div>

      <span style="color:#999">|</span>

      <button type="button" class="am-btn am-btn-default am-btn-sm" style="border:1px transparent; background-color: transparent; color:#999" data-am-modal="{target: '#my-alert2'}">
        关于
      </button>

      <div class="am-modal am-modal-alert" tabindex="-1" id="my-alert2">
        <div class="am-modal-dialog">
          <div class="am-modal-hd">关于</div>
          <div class="am-modal-bd">
            者也，一起提高姿势水平！<br>
            © 2016 Morocco Group. Developed with Ruby on Rails.<br>
            Group members: 骆铮 宋肇哲 瞿文浩 张福明 黄河
          </div>
          <div class="am-modal-footer">
            <span class="am-modal-btn">确定</span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="am-u-sm-2"></div>
</footer>

app/views/shared/_login_modal.html.erb
<div class="am-modal am-modal-no-btn" tabindex="-1" id="doc-modal-1">
  <div class="am-modal-dialog">
    <div class="am-modal-hd" style="margin: 5px 0 15px;">登录
      <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close>&times;</a>
    </div>
    <iframe src="<%= log_in_url %>" style="height: 135px;"></iframe>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header class="am-topbar am-topbar-inverse am-topbar-fixed-top">
  <h1 class="am-topbar-brand" style="margin-left: 16%">
    <a href="/questions">
      <%=image_tag 'header_tran.png', style: 'padding-bottom: 4px', height: "40px" %>
    </a>
  </h1>

  <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only" data-am-collapse="{target: '#doc-topbar-collapse'}"><span class="am-sr-only">导航切换</span> <span class="am-icon-bars"></span></button>

  <div class="am-collapse am-topbar-collapse" id="doc-topbar-collapse">
    <form class="am-topbar-form am-topbar-left am-form-inline" role="search" action="<%= search_index_url %>" method="get">
      <div class="am-input-group am-input-group-primary" style="min-width: 300px;" >

        <input type="search" class="am-form-field am-input-sm" name="query" placeholder="搜索" style="border-radius:10px;">
      </div>
    </form>

    <% if current_user %>
      <div class="am-topbar-right" style="margin-right: 15%">
        <%= button_to '提问', new_question_path, :id => 'button_ask', :class => 'am-btn am-btn-primary am-topbar-btn am-btn-sm', :method => :get, form_class: 'am-topbar-left am-topbar-inline' %>
        <div class="am-dropdown" data-am-dropdown="{boundary: '.am-topbar'}">
          <button class="am-btn am-btn-secondary am-topbar-btn am-btn-sm am-dropdown-toggle" data-am-dropdown-toggle><%= current_user.login %><span class="am-icon-caret-down"></span></button>
          <ul class="am-dropdown-content">
            <li><%= link_to '我的主页', me_path %></li>
            <li><%= link_to "我的提问", all_questions_user_path(current_user) %></li>
            <li><%= link_to "我的回答", all_answers_user_path(current_user) %></li>
            <li><%= link_to "我的评论", all_comments_user_path(current_user) %></li>
            <li><%= link_to "我赞成的", all_upvotes_user_path(current_user) %></li>
            <li><%= link_to "我反对的", all_downvotes_user_path(current_user) %></li>
            <li><%= link_to '退出', log_out_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    <% else %>
      <div class="am-topbar-right" style="margin-right: 16%">
        <%= button_to '登录', 'javascript:void(0)', :id => 'button_login', :class => 'am-btn am-btn-primary am-topbar-btn am-btn-sm', :method => :get, data:{'am-modal' => "{target: '#doc-modal-1', closeViaDimmer: 0, width: 400, height: 225}"}, form_class: 'am-topbar-right am-topbar-inline' %>
        <%= button_to '注册', 'javascript:void(0)', :id => 'button_signup', :class => 'am-btn am-btn-primary am-topbar-btn am-btn-sm', :method => :get, data:{'am-modal'=> "{target: '#doc-modal-2', closeViaDimmer: 0, width: 400, height: 275}"}, form_class: 'am-topbar-right am-topbar-inline' %>
      </div>
    <% end %>
  </div>
</header>

app/views/shared/_share_box.html.erb
<div class="am-dropdown" data-am-dropdown>
  <button class="am-btn am-btn-sm am-btn-xs am-dropdown-toggle am-icon-share-square-o" style="background-color: transparent;color:#999;" data-am-dropdown-toggle>分享</button>
  <ul class="am-dropdown-content">
    <div class="bdsharebuttonbox">
      <li><a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone"></a></li>
      <li><a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina"></a></li>
      <li><a title="分享到腾讯微博" href="#" class="bds_tqq" data-cmd="tqq"></a></li>
      <li><a title="分享到人人网" href="#" class="bds_renren" data-cmd="renren"></a></li>
      <li><a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin"></a></li>
    </div>
  </ul>
</div>
<script>
  window._bd_share_config={"common":{"bdSnsKey":{},"bdText":document.title ,"bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"1","bdSize":"24"},"share":{}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
</script>

app/views/shared/_signup_modal.erb
<div class="am-modal am-modal-no-btn" tabindex="-1" id="doc-modal-2">
  <div class="am-modal-dialog">
    <div class="am-modal-hd" style="margin:5px 0 15px;">注册
      <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close>&times;</a>
    </div>
    <div class="am-modal-bd">
      <iframe src="<%= new_user_path %>", style="height:180px;"></iframe>
    </div>
  </div>
</div>