config/routes.rb
Rails.application.routes.draw do
  resources :votes
  get 'search/index'

  resources :answers
  mount Ckeditor::Engine => '/ckeditor'
  get 'portal/index'

  resources :questions do
    resources :question_comments
    get 'question_votes', to: 'question_votes#index'
    post 'question_votes', to: 'question_votes#handle', as: :question_vote
    resources :answers do
      get 'answer_votes', to: 'answer_votes#index'
      post 'answer_votes', to: 'answer_votes#handle', as: :answer_vote
      resources :answer_comments
    end
  end

  resources :users do
    member do
      get 'all_questions'
      get 'all_answers'
      get 'all_comments'
      get 'all_downvotes'
      get 'all_upvotes'
    end
  end

  resources :user_sessions, only: [:create, :destroy]

  delete '/logout', to: 'user_sessions#destroy', as: :log_out
  get '/login', to: 'user_sessions#new', as: :log_in

  get '/me', to: 'users#cur_user'

   root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
    validates_length_of :content, minimum: 10, maximum: 2000
    validates_presence_of :user_id
    validates_uniqueness_of :user_id, scope: :question_id
    belongs_to :user
    belongs_to :question
    has_many :answer_comments, dependent: :destroy
    has_many :answer_votes, dependent: :destroy

    before_save :sanitize_content
    before_update :sanitize_content

    after_create :calculate_score

    after_find do |answer|
      old_score = answer.score
      answer.calculate_score
      if old_score != answer.score
        answer.save
      end
    end

    searchable do
        text :content, :stored => true
    end

    def points
        AnswerVote.where(answer: self).sum(:attitude)
    end

    private

    def sanitize_content
        self.content = Sanitize.fragment(self.content, Sanitize::Config::RELAXED)
    end

    public
      def calculate_score
          logger.debug "answer calculate score start"
          u = Float(answer_votes.where(attitude: 1).length)
          v = Float(answer_votes.where(attitude: -1).length)
          n = u + v

          vote_score = 0.0

          if (n != 0)
              p = u / n
              z = 1.96

              vote_score = 4 * n * (1 - p) * p + z ** 2
              vote_score = Math.sqrt(vote_score)
              vote_score = vote_score * z / n / 2
              vote_score = p + z ** 2 / 2 / n - vote_score
              vote_score = vote_score / (1 + z ** 2 / n)
          end

        comment_score = 0.0
        cnt = 0

        answer_comments.order(score: :desc).each do |comment|
            next if comment.user_id == self.user_id
            cnt += 1
            comment_score += comment.score
            break if cnt == 100
        end

        comment_score /= 100

        begin
            date_diff = (DateTime.now - created_at).to_i
        rescue
            date_diff = 0
        end

        self.score = vote_score * 0.7 + comment_score * 0.3

        if date_diff < 10
            self.score += 0.02 * (10 - date_diff)
        end

        logger.debug "answer calculate score success"

        self.score
      end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :get_answer, :only => [:update,:show,:edit,:destroy]
  before_action :get_question, :only => [:index,:create,:new,:update,:show,:edit,:destroy]
  authorize_resource

  respond_to :html, :js

  layout false
  # Display all answers to a question
  def get_answer
    @answer = Answer.find(params[:id])
  end
  def get_question
    @question = Question.find(params[:question_id])
  end
  def index
    @answers = Answer.where(question: @question)
    @sort = params[:sort]
  end

  # Action: Create a new answer
  def create
    @answer = Answer.new(answer_params)
    @answer.user = current_user
    @answer.question = @question
    authorize! :create, @answer
    @answer.save
    render 'answers/create'
  end

  # Display an answer box to current question
  def new
    @answer = Answer.new
  end

  # Display an item of answer
  def show
  end

  # Display form to edit current answer
  def edit
    authorize! :update, @answer
  end

  # Action: Update given answer
  def update
    @answer.update(answer_params)
    redirect_to @question
  end

  # Action: Destroy current answer
  # Require answer.id == current_user.login || admin access
  def destroy
    @answer.destroy
    redirect_to root_path
  end
  private
  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer_box.html.erb
<% if ! defined? show_without_html %>
    <% show_without_html = false %>
<% end %>

<% if detail %>
    <div class="am-u-sm-3"></div>
    <div class="am-u-sm-9 am-u-sm-offset-3">
      <div>
        <%= link_to question_path(@answer.question) do %>
            <span class="am-monospace" style="font-weight: bold; font-size: 1.1em;"><%= @answer.question.title %></span>
        <% end %>
      </div>
    </div>

    <div id="answer-<%= @answer.id %>">
      <div class="am-g">
        <div class="am-u-sm-3">
          <% @vote = AnswerVote.user_vote(current_user, @answer.id) %>
          <%= render 'votes/vote_box' %>
        </div>
        <div class="am-u-sm-9">
          <div style="display: inline-block; padding-top: 0.3em;">
            <%= link_to render(partial: 'users/user_name', locals: {user: @answer.user}), @answer.user, data: {'user-login'=> @answer.user.login}, class: "user-in-answer" %>
          </div>
          <div style="display: inline-block; float: right; padding-top: 0.3em;">
            <% if can? :update, @answer %>
                <%= link_to '修改', edit_question_answer_path(@answer.question, @answer), remote: true %>
            <% end %>
          </div>
          <% if show_without_html %>
              <div class="answer_wrapper" style="margin-top: 0.3em; margin-bottom: 0.3em;"><%= @answer.content %></div>
          <% else %>
              <div class="answer_wrapper" style="margin-top: 0.3em; margin-bottom: 0.3em;"><%= @answer.content.html_safe %></div>
          <% end %>
          <div style="display: inline-block">
            <a id="answer<%= @answer.id %>_comment_link" data-answer-id="<%= @answer.id %>" data-question-id="<%= @answer.question.id %>"
               href="javascript: void(0)" class="am-icon-comment-o" style="font-size:1.4rem; color:#999;"><%= @answer.answer_comments.length %>条评论</a>
            <%= render 'shared/share_box' %>
          </div>
          <div style="display: inline-block; float: right">
            <span style="font-size: 1.4rem; color:rgb(153, 153, 153)">发布于<%= @answer.created_at.strftime("%Y/%m/%d") %></span>
          </div>
          <div id="answer<%= @answer.id %>_comments_placeholder"></div>
          <hr>
        </div>
      </div>
    </div>

<% else %>

    <div id="answer-<%= @answer.id %>">
      <div class="am-g">
        <div class="am-u-sm-3">
          <% @vote = AnswerVote.user_vote(current_user, @answer.id) %>
          <%= render 'votes/vote_box' %>
        </div>
        <div class="am-u-sm-9">
          <div style="display: inline-block; padding-top: 0.3em;">
            <%= link_to render(partial: 'users/user_name', locals: {user: @answer.user}), @answer.user, data: {'user-login'=> @answer.user.login}, class: "user-in-answer" %>
          </div>
          <div style="display: inline-block; float: right; padding-top: 0.3em;">
            <% if can? :update, @answer %>
                <%= link_to '修改', edit_question_answer_path(@answer.question, @answer), remote: true %>
            <% end %>
          </div>
          <div class="answer_wrapper" style="margin-top: 0.3em; margin-bottom: 0.3em;"><%= @answer.content.html_safe %></div>
          <div style="display: inline-block">
            <a id="answer<%= @answer.id %>_comment_link" data-answer-id="<%= @answer.id %>" data-question-id="<%= @answer.question.id %>"
               href="javascript: void(0)" class="am-icon-comment-o" style="font-size:1.4rem; color:#999;"><%= @answer.answer_comments.length %>条评论</a>
            <%= render 'shared/share_box' %>
          </div>
          <div style="display: inline-block; float: right">
            <span style="font-size: 1.4rem; color:rgb(153, 153, 153)">发布于<%= @answer.created_at.strftime("%Y/%m/%d") %></span>
          </div>
          <div id="answer<%= @answer.id %>_comments_placeholder"></div>
          <hr>
        </div>
      </div>
    </div>

<% end %>

app/views/answers/_edit.html.erb
<%= render 'errors' %>

<div>
  <div class="am-u-sm-3"></div>
  <div class="am-u-sm-9 am-u-sm-offset-3">
    <span class="am-monospace" style="font-weight: bold; font-size: 1.1em">修改回答</span>
    <hr style="margin-top: 0px;">
    <%= form_for [@question, @answer] do |f| %>
        <%= f.cktext_area :content%>
        <div style="margin-top: 10px;">
          <%= f.submit "提交", class:"am-btn am-btn-primary", style:"float:right"%>
        </div>
    <% end %>
    <!--
    <%= button_to '返回', @question, action:"show", method: :get , :class => 'am-btn', :style => 'float:right; margin-right:5px'%>
    -->
  </div>
</div>

app/views/answers/_errors.html.erb
<div id="answer-error" class="am-alert am-alert-warning" style="visibility: hidden" data-am-alert>
  <% if @answer.errors.any? %>
      <button type="button" class="am-close">&times;</button>
      <h3>警告</h3>

      <ul>
        <% @answer.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>
</div>

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/_show.html.erb
<%= render partial: 'answer_box', locals: {detail: false} %>

app/views/answers/create.js.erb
<% if @answer.errors.any? %>
$("#answer-error")[0].outerHTML = "<%= j render 'answers/errors' %>";
$("#answer-error").show();
$("#answer-error").css("visibility", "")
<% else %>
location.reload();
<% end %>

app/views/answers/edit.html.erb
<%= render 'errors' %>

<div class="am-g am-g-collapse">
  <div class="am-u-sm-2"></div>
  <div class="am-u-sm-6 am-u-sm-offset-2">
    <span class="am-monospace" style="font-weight: bold">修改回答</span>
    <hr style="margin-top: 0px;">
    <%= form_for [@question, @answer] do |f| %>
        <div style="margin-bottom: 5px">
          <%= f.cktext_area :content%><br>
        </div>
        <%= f.submit "提交", class:"am-btn am-btn-primary", style:"float:right"%>
    <% end %>
    <%= button_to '返回', @question, action:"show", method: :get , :class => 'am-btn', :style => 'float:right; margin-right:5px'%>
  </div>
  <div class="am-u-sm-2">
    <span></span>
  </div>
  <div class="am-u-sm-2"></div>
</div>

app/views/answers/edit.js.erb
answer = $("#answer-<%= @answer.id %>");
answer[0].outerHTML = "<%= j render 'edit'%>";
CKEDITOR.replace('answer_content');

app/views/answers/index.html.erb
<div id="answersheader">
  <div class="am-u-sm-3"></div>
  <div class="am-u-sm-9 am-u-sm-offset-3">
    <div style="display: inline-block; vertical-align: middle">
      <span class="am-monospace" style="font-weight: bold; font-size: 1.1em"><%= @answers.length %>个回答</span>
    </div>
    <div style="display: inline-block; float: right; vertical-align: middle">
      <% if @sort == "1" %>
          <div class="am-btn-group doc-js-btn-1" data-am-button>
            <label class="am-btn am-btn-secondary am-btn-sm am-active">
              <input type="radio" name="options" value="1" id="option1" checked> 综合排序
            </label>
            <label class="am-btn am-btn-secondary am-btn-sm">
              <input type="radio" name="options" value="2" id="option2"> 时间排序
            </label>
          </div>
      <% else %>
          <div class="am-btn-group doc-js-btn-1" data-am-button>
            <label class="am-btn am-btn-secondary am-btn-sm">
              <input type="radio" name="options" value="1" id="option1"> 综合排序
            </label>
            <label class="am-btn am-btn-secondary am-btn-sm am-active">
              <input type="radio" name="options" value="2" id="option2" checked> 时间排序
            </label>
          </div>
      <% end %>
    </div>
    <hr>
  </div>
</div>
</div>

<script>
  // 获取选中的值
  $(function() {
    var $radios = $('[name="options"]');
    $radios.on('change',function() {
      console.log('单选框当前选中的是：', $radios.filter(':checked').val());
      window.location.href = changeURLArg(window.location.href, 'sort', $radios.filter(':checked').val());
    });
  });
</script>

<% if @sort == "1" %>
    <div id="answerslist">
      <% @answers.order("score DESC").each do |answer| %>
          <% @answer = answer %>
          <%= render "answers/show" %>
      <% end %>
    </div>
<% else %>
    <div id="answerslist">
      <% @answers.order("created_at DESC").each do |answer| %>
          <% @answer = answer %>
          <%= render "answers/show" %>
      <% end %>
    </div>
<% end %>

<script>
  function changeURLArg(url, arg, arg_val) {
    var pattern = arg + '=([^&]*)';
    var replaceText = arg + '=' + arg_val;
    if (url.match(pattern)) {
      var tmp = '/(' + arg + '=)([^&]*)/gi';
      tmp = url.replace(eval(tmp), replaceText);
      return tmp;
    }else{
      if(url.match('[\?]')){
        return url + '&' + replaceText;
      }else{
        return url + '?' + replaceText;
      }
    }
    return url + '\n' + arg + '\n' + arg_val;
  }
</script>

<script>
  $(document).ready(function() {
        console.log(window.location.href);
        console.log("log");
      }
  );
</script>

<% logger.debug("hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh") %>
<% logger.debug(request.fullpath) %>
<% logger.debug("hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh") %>

app/views/answers/new.html.erb
<%= render 'errors' %>

<div>
  <div class="am-u-sm-3"></div>
  <div class="am-u-sm-9 am-u-sm-offset-3">
    <span class="am-monospace" style="font-weight: bold">你的回答</span>
    <hr style="margin-top: 0px;">
    <%= form_for [@question, @answer], remote: true do |f| %>
        <%= f.cktext_area :content%>
        <div style="margin-top: 10px;">
          <%= f.submit "提交", class:"am-btn am-btn-primary", style:"float:right"%>
        </div>
    <% end %>
  </div>
</div>

app/views/answers/show.html.erb
<div class="am-g am-g-collapse">
  <div class="am-u-sm-2">
    <div style="width: 50px; float: right; text-align: center; padding-top: 5px;">
      <a href="##" class="am-icon-btn am-primary am-icon-arrow-up am-icon-btn-sm"></a>
      <br>
      <span>23</span>
      <br>
      <a href="##" class="am-icon-btn am-primary am-icon-arrow-down am-icon-btn-sm"></a>
    </div>
  </div>
  <div class="am-u-sm-6">
    <div style="display: inline-block">
      <a href="##"><%= @answer.user.login %></a>
      <span>21</span>
    </div>
    <div style="display: inline-block; float: right">
      <%= link_to '修改', edit_answer_path(@answer) %>
    </div>
    <p class="am-san-serif" style="margin-top: 0;"><%= @answer.content.html_safe%></p>
    <div style="display: inline-block">
      <a href="##">3条评论</a>
      <a href="##">添加评论</a>
      <a href="##">分享</a>
    </div>
    <div style="display: inline-block; float: right">
      <span>发布于<%= @answer.created_at%></span>
    </div>
    <hr>
  </div>
  <div class="am-u-sm-2">
    <span></span>
  </div>
  <div class="am-u-sm-2"></div>
</div>